#### algumas coisas que é bom lembrar
- loss: Função de perda, para avaliar o erro, normalmente usamo o MSE( media do erro quadratico )
- optmizer: Otimizador de ajuste dos pesos da Rede, no caso o ADAM é ( gradiente decendente estocastico )
- metrics: A metrica que a rede vai utilizar para avaliar a performance

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import confusion_matrix

In [6]:
!python -V ou python --version

Python 3.9.12


In [9]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
     ---------------------------------------- 0.0/272.8 MB ? eta -:--:--
     --------------------------------------- 0.3/272.8 MB 17.3 MB/s eta 0:00:16
     ---------------------------------------- 0.8/272.8 MB 9.8 MB/s eta 0:00:28
     --------------------------------------- 1.3/272.8 MB 10.5 MB/s eta 0:00:26
     --------------------------------------- 1.6/272.8 MB 10.2 MB/s eta 0:00:27
     ---------------------------------------- 1.9/272.8 MB 8.5 MB/s eta 0:00:32
     ---------------------------------------- 2.1/272.8 MB 8.5 MB/s eta 0:00:32
     ---------------------------------------- 2.4/272.8 MB 8.1 MB/s eta 0:00:34
     ---------------------------------------- 2.7/272.8 MB 7.4 MB/s eta 0:00:37
     ---------------------------------------- 2.9/272.8 MB 7.2 MB/s eta 0:00:38
     ---------------------------------------- 3.2/272.8 MB 7.4 MB/s eta 0:00:37
      --------------------------------------- 3.6/272.

In [10]:
!pip install keras

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
     ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
     --------- ------------------------------ 0.4/1.7 MB 8.3 MB/s eta 0:00:01
     ---------------------- ----------------- 0.9/1.7 MB 9.9 MB/s eta 0:00:01
     ------------------------------- -------- 1.4/1.7 MB 9.5 MB/s eta 0:00:01
     -------------------------------------- - 1.6/1.7 MB 8.7 MB/s eta 0:00:01
     ---------------------------------------- 1.7/1.7 MB 9.0 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


In [11]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [13]:
dataset = pd.read_csv('../dados/spam/spam.csv')
dataset.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

# tratamento de dados
### aqui é um problema de classificação se é ou não SPAM
### transforma em numeros

### transforma as respostas

In [14]:
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(dataset['Category'])

### pega os textos

In [17]:
mensagens = dataset['Message'].values

### separa em treino e teste

In [18]:
X_traino, X_teste, y_treino, y_teste = train_test_split(mensagens, y, test_size=0.3)

### vetorizar as menssagens

In [19]:
vetorizador = CountVectorizer()
vetorizador.fit(X_traino)
X_traino = vetorizador.transform(X_traino)
X_teste = vetorizador.transform(X_teste)
print(X_traino.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### O que é feito aqui é um seguinte, é uma lista que quando a palavra aparece no indice ele marca como 1

In [20]:
import numpy as np

In [23]:
np.set_printoptions(threshold=np.inf)
X_traino.toarray()[5]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

### iniciando o modelo

In [29]:
modelo = Sequential()

### camadas densas

#### para textos presisamos de um input_dim dinamico, logo quando vetorizamos podemos passar o tamanho do nosso vetor de texto

In [27]:
input_camada = X_traino.shape[1]

In [30]:
modelo.add(Dense(units=10, activation="relu", input_dim=input_camada))
modelo.add(Dropout(0.1))
modelo.add(Dense(units=8, activation="relu"))
modelo.add(Dropout(0.1))
modelo.add(Dense(units=1, activation="sigmoid"))

### após o modelo criado precisamos compilar o modelo

In [31]:
modelo.compile(loss="mean_squared_error", optimizer="adam", metrics=["accuracy"])

In [32]:
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                71360     
                                                                 
 dropout (Dropout)           (None, 10)                0         
                                                                 
 dense_1 (Dense)             (None, 8)                 88        
                                                                 
 dropout_1 (Dropout)         (None, 8)                 0         
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 71,457
Trainable params: 71,457
Non-trainable params: 0
_________________________________________________________________


treinando o modelo

In [33]:
modelo.fit(X_traino, y_treino, epochs=40, batch_size=15, verbose=True, validation_data=(X_teste, y_teste))

Epoch 1/40
260/260 [==============================] - 1s 2ms/step - loss: 0.0956 - accuracy: 0.9092 - val_loss: 0.0253 - val_accuracy: 0.9827
Epoch 2/40
260/260 [==============================] - 1s 2ms/step - loss: 0.0183 - accuracy: 0.9849 - val_loss: 0.0124 - val_accuracy: 0.9874
Epoch 3/40
260/260 [==============================] - 1s 2ms/step - loss: 0.0082 - accuracy: 0.9941 - val_loss: 0.0110 - val_accuracy: 0.9874
Epoch 4/40
260/260 [==============================] - 0s 2ms/step - loss: 0.0047 - accuracy: 0.9951 - val_loss: 0.0105 - val_accuracy: 0.9880
Epoch 5/40
260/260 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 0.9956 - val_loss: 0.0104 - val_accuracy: 0.9874
Epoch 6/40
260/260 [==============================] - 1s 2ms/step - loss: 0.0025 - accuracy: 0.9974 - val_loss: 0.0106 - val_accuracy: 0.9892
Epoch 7/40
260/260 [==============================] - 0s 2ms/step - loss: 0.0023 - accuracy: 0.9987 - val_loss: 0.0109 - val_accuracy: 0.9886
Epoch 

#### para avaliação do modelo

In [35]:
loss, accuracy = modelo.evaluate(X_teste, y_teste)
print(f"loss: {loss}\n accuracy: {accuracy}")

53/53 [==============================] - 0s 962us/step - loss: 0.0120 - accuracy: 0.9868
loss: 0.0120308306068182
 accuracy: 0.9868420958518982


In [40]:
nova_previsao = modelo.predict(X_teste)
e_spam = (nova_previsao>0.7)
print(e_spam)

53/53 [==============================] - 0s 808us/step
[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]


### matriz de confusao

In [42]:
cm = confusion_matrix(y_teste, e_spam)
print(cm)

[[1448    2]
 [  19  203]]


In [43]:
modelo.save("../modelo.h5")

# tipos de embedding
- input_dim = Tamanho de entradas do vocabulo
- output_dim = Tamanho do vetor denso
- input_length = tamanho maximo da sequência

## para imagens
- camada Embedding devem ser conectadas a uma camada Flatten
- camada Flatten conectada a Densa